project_id = "lgeaktqexhxejtbjhzdh"

[functions.generate-image]
verify_jwt = false

[functions.edit-image]
verify_jwt = false

[functions.generate-kling-video]
verify_jwt = false

[functions.poll-video-job]
verify_jwt = false
