/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiPublicVcProbeRouteImport } from './routes/api/public/vc-probe'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as ApiPublicPlanTickRouteImport } from './routes/api/public/plan-tick'
import { Route as ApiPublicPlanSchedulerTickRouteImport } from './routes/api/public/plan-scheduler-tick'
import { Route as ApiPublicMediaPollTickRouteImport } from './routes/api/public/media-poll-tick'
import { Route as ApiPublicChatTurnTickRouteImport } from './routes/api/public/chat-turn-tick'
import { Route as ApiPublicSbSplatRouteImport } from './routes/api/public/sb/$'
import { Route as ApiPublicMcpBridgeResultRouteImport } from './routes/api/public/mcp-bridge/result'
import { Route as ApiPublicMcpBridgePollRouteImport } from './routes/api/public/mcp-bridge/poll'
import { Route as ApiPublicMcpBridgePairRouteImport } from './routes/api/public/mcp-bridge/pair'
import { Route as ApiPublicMcpBridgeInstallRouteImport } from './routes/api/public/mcp-bridge/install'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicVcProbeRoute = ApiPublicVcProbeRouteImport.update({
  id: '/api/public/vc-probe',
  path: '/api/public/vc-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlanTickRoute = ApiPublicPlanTickRouteImport.update({
  id: '/api/public/plan-tick',
  path: '/api/public/plan-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlanSchedulerTickRoute =
  ApiPublicPlanSchedulerTickRouteImport.update({
    id: '/api/public/plan-scheduler-tick',
    path: '/api/public/plan-scheduler-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaPollTickRoute = ApiPublicMediaPollTickRouteImport.update({
  id: '/api/public/media-poll-tick',
  path: '/api/public/media-poll-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatTurnTickRoute = ApiPublicChatTurnTickRouteImport.update({
  id: '/api/public/chat-turn-tick',
  path: '/api/public/chat-turn-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSbSplatRoute = ApiPublicSbSplatRouteImport.update({
  id: '/api/public/sb/$',
  path: '/api/public/sb/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpBridgeResultRoute =
  ApiPublicMcpBridgeResultRouteImport.update({
    id: '/api/public/mcp-bridge/result',
    path: '/api/public/mcp-bridge/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMcpBridgePollRoute = ApiPublicMcpBridgePollRouteImport.update({
  id: '/api/public/mcp-bridge/poll',
  path: '/api/public/mcp-bridge/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpBridgePairRoute = ApiPublicMcpBridgePairRouteImport.update({
  id: '/api/public/mcp-bridge/pair',
  path: '/api/public/mcp-bridge/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpBridgeInstallRoute =
  ApiPublicMcpBridgeInstallRouteImport.update({
    id: '/api/public/mcp-bridge/install',
    path: '/api/public/mcp-bridge/install',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/media': typeof AuthenticatedMediaRoute
  '/api/public/chat-turn-tick': typeof ApiPublicChatTurnTickRoute
  '/api/public/media-poll-tick': typeof ApiPublicMediaPollTickRoute
  '/api/public/plan-scheduler-tick': typeof ApiPublicPlanSchedulerTickRoute
  '/api/public/plan-tick': typeof ApiPublicPlanTickRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/vc-probe': typeof ApiPublicVcProbeRoute
  '/api/public/mcp-bridge/install': typeof ApiPublicMcpBridgeInstallRoute
  '/api/public/mcp-bridge/pair': typeof ApiPublicMcpBridgePairRoute
  '/api/public/mcp-bridge/poll': typeof ApiPublicMcpBridgePollRoute
  '/api/public/mcp-bridge/result': typeof ApiPublicMcpBridgeResultRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/media': typeof AuthenticatedMediaRoute
  '/api/public/chat-turn-tick': typeof ApiPublicChatTurnTickRoute
  '/api/public/media-poll-tick': typeof ApiPublicMediaPollTickRoute
  '/api/public/plan-scheduler-tick': typeof ApiPublicPlanSchedulerTickRoute
  '/api/public/plan-tick': typeof ApiPublicPlanTickRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/vc-probe': typeof ApiPublicVcProbeRoute
  '/api/public/mcp-bridge/install': typeof ApiPublicMcpBridgeInstallRoute
  '/api/public/mcp-bridge/pair': typeof ApiPublicMcpBridgePairRoute
  '/api/public/mcp-bridge/poll': typeof ApiPublicMcpBridgePollRoute
  '/api/public/mcp-bridge/result': typeof ApiPublicMcpBridgeResultRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/api/public/chat-turn-tick': typeof ApiPublicChatTurnTickRoute
  '/api/public/media-poll-tick': typeof ApiPublicMediaPollTickRoute
  '/api/public/plan-scheduler-tick': typeof ApiPublicPlanSchedulerTickRoute
  '/api/public/plan-tick': typeof ApiPublicPlanTickRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/vc-probe': typeof ApiPublicVcProbeRoute
  '/api/public/mcp-bridge/install': typeof ApiPublicMcpBridgeInstallRoute
  '/api/public/mcp-bridge/pair': typeof ApiPublicMcpBridgePairRoute
  '/api/public/mcp-bridge/poll': typeof ApiPublicMcpBridgePollRoute
  '/api/public/mcp-bridge/result': typeof ApiPublicMcpBridgeResultRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/media'
    | '/api/public/chat-turn-tick'
    | '/api/public/media-poll-tick'
    | '/api/public/plan-scheduler-tick'
    | '/api/public/plan-tick'
    | '/api/public/tts'
    | '/api/public/vc-probe'
    | '/api/public/mcp-bridge/install'
    | '/api/public/mcp-bridge/pair'
    | '/api/public/mcp-bridge/poll'
    | '/api/public/mcp-bridge/result'
    | '/api/public/sb/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/media'
    | '/api/public/chat-turn-tick'
    | '/api/public/media-poll-tick'
    | '/api/public/plan-scheduler-tick'
    | '/api/public/plan-tick'
    | '/api/public/tts'
    | '/api/public/vc-probe'
    | '/api/public/mcp-bridge/install'
    | '/api/public/mcp-bridge/pair'
    | '/api/public/mcp-bridge/poll'
    | '/api/public/mcp-bridge/result'
    | '/api/public/sb/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/media'
    | '/api/public/chat-turn-tick'
    | '/api/public/media-poll-tick'
    | '/api/public/plan-scheduler-tick'
    | '/api/public/plan-tick'
    | '/api/public/tts'
    | '/api/public/vc-probe'
    | '/api/public/mcp-bridge/install'
    | '/api/public/mcp-bridge/pair'
    | '/api/public/mcp-bridge/poll'
    | '/api/public/mcp-bridge/result'
    | '/api/public/sb/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicChatTurnTickRoute: typeof ApiPublicChatTurnTickRoute
  ApiPublicMediaPollTickRoute: typeof ApiPublicMediaPollTickRoute
  ApiPublicPlanSchedulerTickRoute: typeof ApiPublicPlanSchedulerTickRoute
  ApiPublicPlanTickRoute: typeof ApiPublicPlanTickRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  ApiPublicVcProbeRoute: typeof ApiPublicVcProbeRoute
  ApiPublicMcpBridgeInstallRoute: typeof ApiPublicMcpBridgeInstallRoute
  ApiPublicMcpBridgePairRoute: typeof ApiPublicMcpBridgePairRoute
  ApiPublicMcpBridgePollRoute: typeof ApiPublicMcpBridgePollRoute
  ApiPublicMcpBridgeResultRoute: typeof ApiPublicMcpBridgeResultRoute
  ApiPublicSbSplatRoute: typeof ApiPublicSbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/vc-probe': {
      id: '/api/public/vc-probe'
      path: '/api/public/vc-probe'
      fullPath: '/api/public/vc-probe'
      preLoaderRoute: typeof ApiPublicVcProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plan-tick': {
      id: '/api/public/plan-tick'
      path: '/api/public/plan-tick'
      fullPath: '/api/public/plan-tick'
      preLoaderRoute: typeof ApiPublicPlanTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plan-scheduler-tick': {
      id: '/api/public/plan-scheduler-tick'
      path: '/api/public/plan-scheduler-tick'
      fullPath: '/api/public/plan-scheduler-tick'
      preLoaderRoute: typeof ApiPublicPlanSchedulerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-poll-tick': {
      id: '/api/public/media-poll-tick'
      path: '/api/public/media-poll-tick'
      fullPath: '/api/public/media-poll-tick'
      preLoaderRoute: typeof ApiPublicMediaPollTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat-turn-tick': {
      id: '/api/public/chat-turn-tick'
      path: '/api/public/chat-turn-tick'
      fullPath: '/api/public/chat-turn-tick'
      preLoaderRoute: typeof ApiPublicChatTurnTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sb/$': {
      id: '/api/public/sb/$'
      path: '/api/public/sb/$'
      fullPath: '/api/public/sb/$'
      preLoaderRoute: typeof ApiPublicSbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp-bridge/result': {
      id: '/api/public/mcp-bridge/result'
      path: '/api/public/mcp-bridge/result'
      fullPath: '/api/public/mcp-bridge/result'
      preLoaderRoute: typeof ApiPublicMcpBridgeResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp-bridge/poll': {
      id: '/api/public/mcp-bridge/poll'
      path: '/api/public/mcp-bridge/poll'
      fullPath: '/api/public/mcp-bridge/poll'
      preLoaderRoute: typeof ApiPublicMcpBridgePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp-bridge/pair': {
      id: '/api/public/mcp-bridge/pair'
      path: '/api/public/mcp-bridge/pair'
      fullPath: '/api/public/mcp-bridge/pair'
      preLoaderRoute: typeof ApiPublicMcpBridgePairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp-bridge/install': {
      id: '/api/public/mcp-bridge/install'
      path: '/api/public/mcp-bridge/install'
      fullPath: '/api/public/mcp-bridge/install'
      preLoaderRoute: typeof ApiPublicMcpBridgeInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicChatTurnTickRoute: ApiPublicChatTurnTickRoute,
  ApiPublicMediaPollTickRoute: ApiPublicMediaPollTickRoute,
  ApiPublicPlanSchedulerTickRoute: ApiPublicPlanSchedulerTickRoute,
  ApiPublicPlanTickRoute: ApiPublicPlanTickRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  ApiPublicVcProbeRoute: ApiPublicVcProbeRoute,
  ApiPublicMcpBridgeInstallRoute: ApiPublicMcpBridgeInstallRoute,
  ApiPublicMcpBridgePairRoute: ApiPublicMcpBridgePairRoute,
  ApiPublicMcpBridgePollRoute: ApiPublicMcpBridgePollRoute,
  ApiPublicMcpBridgeResultRoute: ApiPublicMcpBridgeResultRoute,
  ApiPublicSbSplatRoute: ApiPublicSbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
